
[colors.bright]
black = "#555555"
blue = "#6fc1ff"
cyan = "#6fc1ff"
green = "#19f9d8"
magenta = "#ff9ac1"
red = "#ff2c6d"
white = "#ffffff"
yellow = "#ffcc95"

[colors.cursor]
cursor = "#ffb86c"
text = "#fefff2"

[colors.normal]
black = "#292a2b"
blue = "#45a9f9"
cyan = "#6fc1ff"
green = "#19f9d8"
magenta = "#ff75b5"
red = "#ff2c6d"
white = "#e6e6e6"
yellow = "#ffb86c"

[colors.primary]
background = "#292a2b"
foreground = "#e6e6e6"

[colors.selection]
background = "#555555"
text = "#e6e6e6"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
title = "Alacritty"

[general]
live_config_reload = true
